# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-17 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Table1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_modelo', models.IntegerField(blank=True, null=True)),
                ('vendedor', models.IntegerField(blank=True, null=True)),
                ('nid', models.IntegerField(blank=True, null=True)),
                ('gondola', models.CharField(blank=True, max_length=64, null=True)),
                ('producto', models.CharField(blank=True, max_length=159, null=True)),
                ('categoria_ipc', models.CharField(blank=True, max_length=8, null=True)),
                ('categoria_ipc_9', models.CharField(blank=True, max_length=9, null=True)),
                ('des_producto', models.CharField(blank=True, max_length=46, null=True)),
                ('contenido', models.CharField(blank=True, max_length=5, null=True)),
                ('divisor', models.CharField(blank=True, max_length=5, null=True)),
                ('multiplo', models.CharField(blank=True, max_length=4, null=True)),
                ('unidades', models.CharField(blank=True, max_length=3, null=True)),
                ('descripcion1', models.CharField(blank=True, max_length=13, null=True)),
                ('descripcion2', models.CharField(blank=True, max_length=18, null=True)),
                ('descripcion3', models.CharField(blank=True, max_length=10, null=True)),
                ('unidadmedida', models.CharField(blank=True, max_length=8, null=True)),
                ('des_marca', models.CharField(blank=True, max_length=21, null=True)),
                ('des_empresa', models.CharField(blank=True, max_length=40, null=True)),
                ('campo', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre', models.IntegerField(blank=True, null=True)),
                ('target', models.CharField(blank=True, max_length=8, null=True)),
                ('likelihood', models.DecimalField(blank=True, decimal_places=8, max_digits=9, null=True)),
                ('timestamp', models.CharField(blank=True, max_length=20, null=True)),
                ('features', models.CharField(blank=True, max_length=8, null=True)),
                ('modelo', models.CharField(blank=True, max_length=16, null=True)),
                ('status', models.CharField(blank=True, db_column='Status', max_length=7, null=True)),
            ],
            options={
                'db_table': 'TABLE 1',
                'managed': False,
            },
        ),
    ]
